"""user table add schema

Revision ID: 0f339e9d058d
Revises: e8ef753e6b86
Create Date: 2024-03-24 23:35:21.789558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f339e9d058d'
down_revision: Union[str, None] = 'e8ef753e6b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('notion_id', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('discord_id', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index('email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'enabled')
    op.drop_column('user', 'discord_id')
    op.drop_column('user', 'notion_id')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'username')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
