"""test

Revision ID: ef31eeadc783
Revises: e8ef753e6b86
Create Date: 2024-03-30 23:49:20.948231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = "ef31eeadc783"
down_revision: Union[str, None] = "0f339e9d058d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the current database."""
    inspector = reflection.Inspector.from_engine(op.get_bind())
    tables = inspector.get_table_names()
    return table_name in tables


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('bingo_boards'):
        op.create_table(
            "bingo_boards",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("board_data", sa.JSON(), nullable=False),
            sa.Column("bingo_count", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("user_id"),
        )
    if not table_exists('bingo_interaction'):
        op.create_table(
            "bingo_interaction",
            sa.Column("interaction_id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("word_id", sa.Integer(), nullable=False),
            sa.Column("send_user_id", sa.Integer(), nullable=False),
            sa.Column("receive_user_id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("interaction_id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bingo_interaction")
    op.drop_table("bingo_boards")
    # ### end Alembic commands ###
