name: Docker Compose CI

on:
  push:
    branches:
      - feature/cd

jobs:
  build:
    runs-on: Windows

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: feature/cd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Shut down Docker Compose
        run: |
          docker compose -f docker-compose.yaml down

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d
